### ISSUE TITLE
preserveMediaQueries not being picked up?

### ISSUE THREAD

**Issue by oskarkrawczyk** [jonkemp/gulp-inline-css#23]
Hi,

Spent the last hour trying to figure out why `preserveMediaQueries` is not being picked up.

Are there any known issues that make this option unusable? 

The code is pretty straightforward:

CSS (compiled from SCSS):

```css
.imageAndText {
  width: 100%; }
  .imageAndText td {
    font-weight: 600; }
    @media screen and (max-width: 375px) {
      .imageAndText td {
        display: block;
        text-align: center;
        width: 100% !important; } }
  .imageAndText .image {
    width: 75px; }
    @media screen and (max-width: 375px) {
      .imageAndText .image {
        padding-bottom: 5px; } }
```

Taks config:

```javascript
gulp.task("html", function(){
  gulp.src("*.html")

  // validate html5
  .pipe(html5Lint())

  // notify error
  .on("error", notify.onError({
    message: "<%= error.message %>",
    title:   "😱 HTML",
    sound:   false
  }))

  // sync browsers
  .pipe(browserSync.reload({
    stream: true
  }))

  .pipe(inlineCss({
    removeStyleTags: false,
    removeLinkTags: false,
    preserveMediaQueries: true
  }))

  .pipe(gulp.dest('build/'));
});
```

There's nothing weird here.

I'm really running out of ideas. Any help would be appreciated.
