### ISSUE TITLE
How to inline multiple css attributes?

### ISSUE THREAD

**Issue by think2011** [jonkemp/gulp-inline-css#30]
```css
.items {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-pack: justify;
    -webkit-justify-content: space-between;
    -ms-flex-pack: justify;
    justify-content: space-between;
}
```

This result is not what I want:
```html
<div style="-ms-flex-pack: justify; -webkit-box-pack: justify; -webkit-justify-content: space-between; display: flex; justify-content: space-between;"></div>
```

And thanks you! this repo very helpful for me : )
